//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.24 at 01:39:54 PM WAT 
//


package com.neptunesoftware.nipintegrator.inward.model.nameenquiry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accountName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bankVerificationNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="kycLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="responseCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "SessionId",
        "DestinationInstitutionCode",
        "ChannelCode",
        "AccountNumber",
        "AccountName",
        "BankVerificationNumber",
        "KycLevel",
        "ResponseCode"
})
@XmlRootElement(name = "NESingleResponse")
public class NESingleResponse {

    @XmlElement(required = true)
    protected String SessionId;
    @XmlElement(required = true)
    protected String DestinationInstitutionCode;
    protected int ChannelCode;
    @XmlElement(required = true)
    protected String AccountNumber;

    @XmlElement(required = true)
    protected String AccountName;
    @XmlElement(required = true)
    protected String BankVerificationNumber;
    @XmlElement(required = true)
    protected String KycLevel;
    @XmlElement(required = true)
    protected String ResponseCode;

    public String getSessionId() {
        return SessionId;
    }

    public void setSessionId(String sessionId) {
        this.SessionId = sessionId;
    }

    public String getDestinationInstitutionCode() {
        return DestinationInstitutionCode;
    }

    public void setDestinationInstitutionCode(String destinationInstitutionCode) {
        this.DestinationInstitutionCode = destinationInstitutionCode;
    }

    public int getChannelCode() {
        return ChannelCode;
    }

    public void setChannelCode(int channelCode) {
        this.ChannelCode = channelCode;
    }

    public String getAccountNumber() {
        return AccountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.AccountNumber = accountNumber;
    }


    /**
     * Gets the value of the accountName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccountName() {
        return AccountName;
    }

    /**
     * Sets the value of the accountName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccountName(String value) {
        this.AccountName = value;
    }

    /**
     * Gets the value of the bankVerificationNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBankVerificationNumber() {
        return BankVerificationNumber;
    }

    /**
     * Sets the value of the bankVerificationNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBankVerificationNumber(String value) {
        this.BankVerificationNumber = value;
    }

    /**
     * Gets the value of the kycLevel property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKycLevel() {
        return KycLevel;
    }

    /**
     * Sets the value of the kycLevel property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKycLevel(String value) {
        this.KycLevel = value;
    }

    /**
     * Gets the value of the responseCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getResponseCode() {
        return ResponseCode;
    }

    /**
     * Sets the value of the responseCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setResponseCode(String value) {
        this.ResponseCode = value;
    }

}
