//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.24 at 01:39:54 PM WAT 
//

//@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.neptunesoftware.com/nipintegrator/inward/model/amountUnblock")
package com.neptunesoftware.nipintegrator.inward.model.amountunblock;
